services:
  db:
    container_name: emprega_db
    image: postgres:13-alpine
    volumes:
      - emprega_base:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 2s
      timeout: 3s
      retries: 40
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  migrate:
    container_name: emprega_migrate
    build: .
    command: python manage.py migrate --noinput
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python manage.py migrate --check --dry-run"
        ]
      interval: 2s
      timeout: 3s
      retries: 40
    depends_on:
      db:
        condition: service_healthy

  web:
    container_name: emprega_web
    build: .
    restart: unless-stopped
    command: sh -c "python manage.py collectstatic --no-input && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src/static:/app/static
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  nginx:
    container_name: emprega_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8073:8073"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/static:/static
      - ./nginx_log:/var/log/nginx
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      VIRTUAL_HOST: api.ceitec.baraus.dev
      VIRTUAL_PORT: 8073
      LETSENCRYPT_HOST: api.ceitec.baraus.dev
      LETSENCRYPT_EMAIL: "me@baraus.dev"
    networks:
      - nginx-proxy
      - default

  redis:
    container_name: emprega_redis
    image: redis:alpine
    
  celery:
    container_name: emprega_celery
    restart: always
    build:
      context: .
    command: celery --app=core worker --loglevel=info -E
    volumes:
      - ./src:/app
    env_file:
      - .env
    environment:
      - OMP_NUM_THREADS=1
    depends_on:
      - db
      - redis
      - web

volumes:
  emprega_nginx:
    external: true
  emprega_base:
    external: true

networks:
  nginx-proxy:
    external: true
  